apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
  labels:
    app: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrybkt9373.azurecr.io/poi:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1
            memory: 256MB
        env:
          - name:  SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  sql
                key:  password
