kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev-access
subjects:
- kind: Group
  namespace: web
  name: 41cfc5d6-ecbf-462c-8791-248d284cf48f

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-access
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-dev-access
subjects:
- kind: Group
  namespace: api
  name: 9bb1d3f6-a5ef-43b6-9cb7-085b43cd7524
