apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  labels:
    run: userprofile-service
  namespace: api
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: userprofile

---
apiVersion: v1
kind: Service
metadata:
  name: trips-service
  labels:
    run: trips-service
  namespace: api
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: trips

---
apiVersion: v1
kind: Service
metadata:
  name: user-java-service
  labels:
    run: user-java-service
  namespace: api
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: user-java

---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
  labels:
    run: poi-service
  namespace: api
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: poi