apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
  labels:
    app: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registrybkt9373.azurecr.io/trips:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1
            memory: 256Mi
        env:
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  sql
                key:  password
          - name: SQL_DBNAME
            valueFrom:
              configMapKeyRef:
                key: sql_dbname
                name: tripviewer-configmap
          - name: SQL_USER
            valueFrom:
              configMapKeyRef:
                key: sql_user
                name: tripviewer-configmap
          - name: SQL_SERVER
            valueFrom:
              configMapKeyRef:
                key: sql_servername
                name: tripviewer-configmap

