apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
  labels:
    app: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registrybkt9373.azurecr.io/userprofile:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1
            memory: 256Mi
        env:
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  sql
                key:  password
          - name: SQL_DBNAME
            valueFrom:
              configMapKeyRef:
                key: sql_dbname
                name: tripviewer-configmap
          - name: SQL_USER
            valueFrom:
              configMapKeyRef:
                key: sql_user
                name: tripviewer-configmap
          - name: SQL_SERVER
            valueFrom:
              configMapKeyRef:
                key: sql_servername
                name: tripviewer-configmap

